project:
  type: website
  output-dir: docs

website:
  title: "Plankton Systematics & Ecology Course"
  navbar:
    title: "AQ 224"
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Lectures"

        menu:
          - text: "Course introduction"
            href: lectures/1_intro.qmd
          - text: "Division of the Ocean"
            href: lectures/2_ocean_divisions.qmd
          - text: "Plankton Importances"
            href: lectures/3_phyto_ecology.qmd
          - text: "Plankton Taxonomy(Cyanobacteria)"
            href: lectures/4_phyto_taxonomy_cyanobacteria.qmd
          - text: "Diatoms Taxonomy"
            href: lectures/5_diatoms_taxonomy.qmd
          - text: "Diatoms Life Cycle"
            href: lectures/6_diatoms_life_cycle.qmd
          - text: "Dinoflagellates Taxonomy"
            href: lectures/7_dinoflagellate_taxonomy.qmd
          - text: "Dinoflagellates Reproduction"
            href: lectures/8_dinoflagellate_reproduction.qmd
          - text: "Harmful Algal Blooms"
            href: lectures/9_harmful_algal_bloom.qmd
          - text: "Types of HABs"
            href: lectures/10_types_of_HABs.qmd
          - text: "Primary Production"
            href: lectures/11_primary_production.qmd
          - text: "Zooplankton Ecology and Taxonomy"
            href: lectures/12_zooplankton_taxonomy.qmd




      - text: "Practicals"
        menu:
          - text: "Phytoplankton Identification"
          #   href: practical/length_weight_practical.qmd
          # - text: "Length-Weight Relationships (Using R)"
          #   href: practical/length_weight_isometric.qmd


      - text: "Assignments"
        menu:
          - text: "Assignment 1"
            href: Assignment/HABs_assignment.qmd
          
      - text: "Resources"
        menu:
          - text: "Data"
            href: resources/data.qmd
          - text: "Glossary"
            href: resources/glossary.qmd
    right:
      - icon: github
        href: https://github.com/nyamisi
        aria-label: GitHub

  sidebar:
    - title: "Course Modules"
      contents:
        - index.qmd
        - section: "Course synopsis"
          contents: 
            - lectures/synopsis.qmd
        # - section: "Module 1: Introduction"
        #   contents:
        #     - lectures/lecture1.qmd
        # - section: "Module 2: Data Collection"
        #   contents:
        #     - lectures/lecture1.qmd
        #     - lectures/lecture2.qmd

  page-footer:
    left: "Plankton Systematics & Ecology Course | AQ 224"
    right: "© 2025/2026 Nyamisi Peter"

format:
  html:
    theme: yeti
    css: styles.css
    toc: true
    toc-depth: 3
    code-fold: false
    code-tools: false